/** Curated list of common default/weak JWT signing secrets. */
export const WEAK_SECRETS: string[] = [
  // Generic weak secrets
  "secret",
  "password",
  "123456",
  "12345678",
  "1234567890",
  "test",
  "key",
  "changeme",
  "admin",
  "default",
  "pass",
  "letmein",
  "qwerty",
  "abc123",
  "iloveyou",
  "welcome",
  "monkey",

  // JWT-specific / tutorial defaults
  "your-256-bit-secret",
  "jwt_secret",
  "jwt-secret",
  "mysecretkey",
  "my-secret-key",
  "my_secret_key",
  "super_secret",
  "super-secret",
  "supersecret",
  "secretkey",
  "secret_key",
  "secret-key",
  "jwt_secret_key",
  "token_secret",
  "auth_secret",
  "signing_key",
  "signingkey",
  "hmac-secret",
  "hs256-secret",
  "jwt_signing_key",

  // Framework / example defaults
  "shhhhhhared-secret",
  "keyboard cat",
  "django_secret",
  "django-insecure-key",
  "express-session-secret",
  "session_secret",
  "app_secret",
  "application_secret",
  "rails_secret",
  "flask-secret",
  "laravel_secret",
  "spring-secret",

  // Developer placeholders
  "CHANGE_ME",
  "changethis",
  "your-secret-here",
  "replace-me",
  "dev-secret",
  "development",
  "testing",
  "staging",
  "placeholder",
  "TODO_CHANGE",
  "PUT_YOUR_SECRET_HERE",
  "xxxxx",
  "yyyyy",

  // Common sample code strings
  "foo",
  "bar",
  "baz",
  "hello",
  "hello world",
  "example",
  "sample",
  "demo",
  "test123",
  "password123",
  "s3cr3t",
  "p@ssw0rd",
  "AllYourBase",
];
